// @flow

export const INITIALIZE_CALENDAR = 'INITIALIZE_CALENDAR';
export const NEXT_MONTH = 'NEXT_MONTH';
export const PREV_MONTH = 'PREV_MONTH';
export const PENDING_APP = 'PENDING_APP';
export const SELECTED_DATE = 'SELECTED_DATE';
export const MODAL_IS_OPEN = 'MODAL_IS_OPEN';
export const ADD_NOTICED = 'ADD_NOTICED';
export const EDIT_NOTICED = 'EDIT_NOTICED';
export const SWITCH_NOTICED_MODAL = 'SWITHC_NOTICED_MODAL';
export const SAVE_CHANGE_NOTICED = 'SAVE_CHANGE_NOTICED';
export const SELECTED_SEARCH_NOTICE = 'SELECTED_SEARCH_NOTICE';

// SET
export const SET_SWITCH_NOTICED_MODAL = 'SET_SWITHC_NOTICED_MODAL';
export const SET_SAVE_CHANGE_NOTICED = 'SET_SAVE_CHANGE_NOTICED';
export const SET_NEXT_MONTH = 'SET_NEXT_MONTH';
export const SET_EDIT_NOTICED = 'SET_EDIT_NOTICED';
export const SET_ADD_NOTICED = 'SET_ADD_NOTICED';
export const SET_MODAL_IS_OPEN = 'SET_MODAL_IS_OPEN';
export const SET_PREV_MONTH = 'SET_PREV_MONTH';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_INITIALIZE_CALENDAR = 'SET_INITIALIZE_CALENDAR';
export const SET_SELECTED_SEARCH_NOTICE = 'SET_SELECTED_SEARCH_NOTICE';
